### ISSUE TITLE
项目导入以后缺少依赖项，请问从哪里下载

### ISSUE THREAD

**Issue by pwnyxz** [cosmoplat-dev/netty-server#3]
Could not resolve dependencies for project com.joker.collector:netty-server:jar:1.0.0: Failure to find com.nhb.utils:nhb-utils:jar:1.0.0 in http://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are forced -> [Help 1]

**Comment by dlsyaim** [comment]
请教下。这个问题怎么解决。能提供Jar包吗

**Comment by andytoward** [comment]
是啊怎么解决啊
